declare module 'lucide-react' {
  import { FC, SVGProps } from 'react'

  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: number | string
    color?: string
    strokeWidth?: number | string
  }

  export type Icon = FC<IconProps>

  export const Send: Icon
  export const FileText: Icon
  export const Loader2: Icon
  export const Table: Icon
  export const History: Icon
  export const Trash2: Icon
  export const Clock: Icon
  export const ChevronDown: Icon
  export const Plus: Icon
  export const Check: Icon
  export const CheckCircle: Icon
  export const XCircle: Icon
  export const Download: Icon
  export const AlertCircle: Icon
  export const Brain: Icon
  export const Database: Icon
  export const Search: Icon
  export const Wrench: Icon
  export const ChevronUp: Icon
  export const X: Icon
  export const Maximize2: Icon
  export const LayoutDashboard: Icon
  export const FileSearch: Icon
  export const Settings: Icon
  export const Menu: Icon
  export const Bell: Icon
  export const User: Icon
  export const LogOut: Icon
  export const MoreVertical: Icon
  export const Upload: Icon
  export const Trash: Icon
  export const Edit: Icon
  export const Eye: Icon
  export const RefreshCw: Icon
  export const Play: Icon
  export const Pause: Icon
  export const Stop: Icon
  export const PlusCircle: Icon
  export const MinusCircle: Icon
  export const HelpCircle: Icon
  export const Info: Icon
  export const Warning: Icon
  export const XCircleIcon: Icon
  export const CheckCircleIcon: Icon
  export const ArrowRight: Icon
  export const ArrowLeft: Icon
  export const ArrowUp: Icon
  export const ArrowDown: Icon
  export const ChevronRight: Icon
  export const ChevronLeft: Icon
  export const SearchIcon: Icon
  export const Filter: Icon
  export const SortAsc: Icon
  export const SortDesc: Icon
  export const MoreHorizontal: Icon
  export const GripVertical: Icon
  export const Layers: Icon
  export const Grid: Icon
  export const List: Icon
  export const Calendar: Icon
  export const ClockIcon: Icon
  export const MapPin: Icon
  export const Mail: Icon
  export const Phone: Icon
  export const Link: Icon
  export const ExternalLink: Icon
  export const Copy: Icon
  export const Share: Icon
  export const Star: Icon
  export const Heart: Icon
  export const ThumbsUp: Icon
  export const ThumbsDown: Icon
  export const MessageSquare: Icon
  export const MessageCircle: Icon
  export const BellIcon: Icon
  export const Home: Icon
  export const Building: Icon
  export const Users: Icon
  export const UserPlus: Icon
  export const UserMinus: Icon
  export const UserCheck: Icon
  export const UserX: Icon
  export const Shield: Icon
  export const ShieldCheck: Icon
  export const ShieldAlert: Icon
  export const Lock: Icon
  export const Unlock: Icon
  export const Key: Icon
  export const EyeIcon: Icon
  export const EyeOff: Icon
  export const File: Icon
  export const FilePlus: Icon
  export const FileMinus: Icon
  export const FileCheck: Icon
  export const FileX: Icon
  export const FileTextIcon: Icon
  export const Folder: Icon
  export const FolderPlus: Icon
  export const FolderMinus: Icon
  export const FolderOpen: Icon
  export const Image: Icon
  export const ImageIcon: Icon
  export const Video: Icon
  export const Music: Icon
  export const Mic: Icon
  export const MicOff: Icon
  export const Camera: Icon
  export const CameraOff: Icon
  export const PhoneCall: Icon
  export const PhoneOff: Icon
  export const PhoneMissed: Icon
  export const Voicemail: Icon
  export const Wifi: Icon
  export const WifiOff: Icon
  export const Bluetooth: Icon
  export const Battery: Icon
  export const BatteryCharging: Icon
  export const BatteryFull: Icon
  export const BatteryMedium: Icon
  export const BatteryLow: Icon
  export const Zap: Icon
  export const Flashlight: Icon
  export const Sun: Icon
  export const Moon: Icon
  export const Cloud: Icon
  export const CloudRain: Icon
  export const CloudSnow: Icon
  export const CloudLightning: Icon
  export const Wind: Icon
  export const Thermometer: Icon
  export const Droplets: Icon
  export const Umbrella: Icon
  export const Snowflake: Icon
  export const Navigation: Icon
  export const Network: Icon
  export const Compass: Icon
  export const Map: Icon
  export const Globe: Icon
  export const Plane: Icon
  export const Car: Icon
  export const Truck: Icon
  export const Ship: Icon
  export const Train: Icon
  export const Bus: Icon
  export const Bike: Icon
  export const Walk: Icon
  export const Run: Icon
  export const Activity: Icon
  export const TrendingUp: Icon
  export const TrendingDown: Icon
  export const BarChart: Icon
  export const PieChart: Icon
  export const LineChart: Icon
  export const AreaChart: Icon
  export const ScatterChart: Icon
  export const Radar: Icon
  export const Target: Icon
  export const Crosshair: Icon
  export const Aperture: Icon
  export const Focus: Icon
  export const ZoomIn: Icon
  export const ZoomOut: Icon
  export const Maximize: Icon
  export const Minimize: Icon
  export const MaximizeIcon: Icon
  export const MinimizeIcon: Icon
  export const Move: Icon
  export const RotateCcw: Icon
  export const RotateCw: Icon
  export const RefreshCcw: Icon
  export const RefreshCwIcon: Icon
  export const Repeat: Icon
  export const Shuffle: Icon
  export const Cast: Icon
  export const Airplay: Icon
  export const Monitor: Icon
  export const Smartphone: Icon
  export const Tablet: Icon
  export const Laptop: Icon
  export const Desktop: Icon
  export const Tv: Icon
  export const Speaker: Icon
  export const Headphones: Icon
  export const Watch: Icon
  export const WatchIcon: Icon
  export const Glasses: Icon
  export const Sunglasses: Icon
  export const Shirt: Icon
  export const ShoppingBag: Icon
  export const ShoppingCart: Icon
  export const CreditCard: Icon
  export const DollarSign: Icon
  export const Euro: Icon
  export const PoundSterling: Icon
  export const JapaneseYen: Icon
  export const IndianRupee: Icon
  export const RussianRuble: Icon
  export const SwissFranc: Icon
  export const ChineseYuan: Icon
  export const Bitcoin: Icon
  export const Banknote: Icon
  export const Wallet: Icon
  export const PiggyBank: Icon
  export const Receipt: Icon
  export const Invoice: Icon
  export const Calculator: Icon
  export const Scale: Icon
  export const Ruler: Icon
  export const Scissors: Icon
  export const Hammer: Icon
  export const WrenchIcon: Icon
  export const Nut: Icon
  export const Bolt: Icon
  export const Cable: Icon
  export const Plug: Icon
  export const PlugZap: Icon
  export const Power: Icon
  export const PowerOff: Icon
  export const ToggleLeft: Icon
  export const ToggleRight: Icon
  export const Sliders: Icon
  export const SlidersHorizontal: Icon
  export const Gauge: Icon
  export const Dashboard: Icon
  export const ActivityIcon: Icon
  export const HeartPulse: Icon
  export const Stethoscope: Icon
  export const Syringe: Icon
  export const Pill: Icon
  export const Capsule: Icon
  export const ThermometerIcon: Icon
  export const FlaskConical: Icon
  export const FlaskRound: Icon
  export const TestTube: Icon
  export const TestTube2: Icon
  export const Atom: Icon
  export const Dna: Icon
  export const DnaOff: Icon
  export const Microscope: Icon
  export const Telescop: Icon
  export const Satellite: Icon
  export const SatelliteDish: Icon
  export const Rocket: Icon
  export const PlaneIcon: Icon
  export const Flame: Icon
  export const FireExtinguisher: Icon
  export const AlertTriangle: Icon
  export const AlertOctagon: Icon
  export const Megaphone: Icon
  export const SpeakerIcon: Icon
  export const Volume: Icon
  export const Volume1: Icon
  export const Volume2: Icon
  export const VolumeX: Icon
  export const VolumeOff: Icon
  export const MusicIcon: Icon
  export const Music2: Icon
  export const Music3: Icon
  export const Music4: Icon
  export const PlayCircle: Icon
  export const PauseCircle: Icon
  export const StopCircle: Icon
  export const SkipBack: Icon
  export const SkipForward: Icon
  export const Rewind: Icon
  export const FastForward: Icon
  export const RepeatIcon: Icon
  export const Repeat1: Icon
  export const ShuffleIcon: Icon
  export const ListMusic: Icon
  export const ListVideo: Icon
  export const ListTodo: Icon
  export const ListChecks: Icon
  export const ListOrdered: Icon
  export const ListStart: Icon
  export const ListEnd: Icon
  export const ListTree: Icon
  export const ListCollapse: Icon
  export const LayoutTemplate: Icon
  export const LayoutGrid: Icon
  export const LayoutList: Icon
  export const LayoutDashboardIcon: Icon
  export const LayoutPanelLeft: Icon
  export const LayoutPanelTop: Icon
  export const FormInput: Icon
  export const Text: Icon
  export const TextIcon: Icon
  export const TextCursor: Icon
  export const TextCursorInput: Icon
  export const TextSelect: Icon
  export const TextQuote: Icon
  export const Type: Icon
  export const Heading: Icon
  export const Heading1: Icon
  export const Heading2: Icon
  export const Heading3: Icon
  export const Heading4: Icon
  export const Heading5: Icon
  export const Heading6: Icon
  export const Pilcrow: Icon
  export const Quote: Icon
  export const Code: Icon
  export const Code2: Icon
  export const Terminal: Icon
  export const TerminalSquare: Icon
  export const Bug: Icon
  export const BugOff: Icon
  export const Braces: Icon
  export const Brackets: Icon
  export const Parentheses: Icon
  export const CurlyBraces: Icon
  export const Divide: Icon
  export const Equal: Icon
  export const EqualNot: Icon
  export const FunctionSquare: Icon
  export const Sigma: Icon
  export const Pi: Icon
  export const Infinity: Icon
  export const Percent: Icon
  export const PercentIcon: Icon
  export const PlusIcon: Icon
  export const Minus: Icon
  export const MinusIcon: Icon
  export const PlusMinus: Icon
  export const XIcon: Icon
  export const DivideIcon: Icon
  export const CalculatorIcon: Icon
  export const Binary: Icon
  export const Hexagon: Icon
  export const Pentagon: Icon
  export const Octagon: Icon
  export const Square: Icon
  export const SquareIcon: Icon
  export const Circle: Icon
  export const CircleIcon: Icon
  export const Triangle: Icon
  export const TriangleIcon: Icon
  export const Diamond: Icon
  export const PentagonIcon: Icon
  export const HexagonIcon: Icon
  export const OctagonIcon: Icon
  export const StarIcon: Icon
  export const HeartIcon: Icon
  export const Sparkles: Icon
  export const ZapIcon: Icon
  export const FlameIcon: Icon
  export const Droplet: Icon
  export const DropletIcon: Icon
  export const Paintbrush: Icon
  export const PaintBucket: Icon
  export const Brush: Icon
  export const Eraser: Icon
  export const PenTool: Icon
  export const Pencil: Icon
  export const Highlighter: Icon
  export const Marker: Icon
  export const Bookmark: Icon
  export const BookmarkIcon: Icon
  export const Tag: Icon
  export const TagIcon: Icon
  export const Tags: Icon
  export const Hash: Icon
  export const AtSign: Icon
  export const Asterisk: Icon
  export const Ampersand: Icon
  export const Crown: Icon
  export const Medal: Icon
  export const Award: Icon
  export const Trophy: Icon
  export const Gift: Icon
  export const GiftIcon: Icon
  export const Package: Icon
  export const PackageIcon: Icon
  export const PackageOpen: Icon
  export const PackageCheck: Icon
  export const PackageX: Icon
  export const Container: Icon
  export const Box: Icon
  export const BoxIcon: Icon
  export const Boxes: Icon
  export const Archive: Icon
  export const ArchiveIcon: Icon
  export const ArchiveRestore: Icon
  export const ArchiveX: Icon
  export const Inbox: Icon
  export const InboxIcon: Icon
  export const MailIcon: Icon
  export const MailOpen: Icon
  export const Paperclip: Icon
  export const PaperclipIcon: Icon
  export const Attachment: Icon
  export const LinkIcon: Icon
  export const Unlink: Icon
  export const Link2: Icon
  export const Link2Off: Icon
  export const Anchor: Icon
  export const AnchorIcon: Icon
  export const Flag: Icon
  export const FlagIcon: Icon
  export const FlagTriangleLeft: Icon
  export const FlagTriangleRight: Icon
  export const Milestone: Icon
  export const Pin: Icon
  export const PinIcon: Icon
  export const Pinned: Icon
  export const PinnedOff: Icon
  export const Locate: Icon
  export const LocateFixed: Icon
  export const LocateOff: Icon
  export const MapIcon: Icon
  export const MapPinIcon: Icon
  export const NavigationIcon: Icon
  export const CompassIcon: Icon
  export const Orientaion: Icon
}
