server:
  port: 8080
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

onlyoffice:
  document-server-url: http://localhost:8088
  public-base-url: http://host.docker.internal:8080
